### ISSUE TITLE
missing dependency Webmozart\Assert in composer.json

### ISSUE THREAD

**Issue by jupitern** [butschster/kraken-api-client#13]
Hi,
i think this dependency is missing from composer.json

Fatal error: Uncaught Error: Class "Webmozart\Assert\Assert" not found in D:\www\tests\kraken\vendor\butschster\kraken-api-client\src\ValueObjects\Enum.php:137

**Comment by butschster** [comment]
@jupitern As I see this dependency is presented in `composer.json`
