### ISSUE TITLE
Support for multiple API keys

### ISSUE THREAD

**Issue by kovinet** [butschster/kraken-api-client#20]
I am building Kraken trading bot, but I will have multi user support. Meaning each user will enter their own Kraken API key in the interface.

What would be the best way to go about this? As I see for now KRAKEN_KEY and KRAKEN_SECRET are loaded directly from environment in the service provider, which makes them global. And I don't see any methods to set them later on runtime...

**Comment by butschster** [comment]
Create a new client instance for each key pair

```php
$client = new \Butschster\Kraken\Client(
    new GuzzleHttp\Client(),
    new \Butschster\Kraken\NonceGenerator(),
    (new \Butschster\Kraken\Serializer\SerializerFactory())->build(),
    'api-key',      // <====== Key
    'api-secret'   // <====== Secret
);
```
